### ISSUE TITLE
Is there any example?

### ISSUE THREAD

**Issue by chengxuntao** [novacrazy/scriptor#3]
I think scriptor is cool.
I'd like to try it.
What is the recommended way to use scriptor?
Stick with Manager?

It would be great, if you can post some examples from real world use case.
Thanks a lot.

**Comment by novacrazy** [comment]
I'm in the process of rewriting all the docs for version 2.0 and I'll be sure to include quite a few full fledged examples. Including a fully fledged server example. 

In the meantime, the only real difference between using the Script class directly or creating them through the Manager is that Scripts created through the Manager can call other scripts via "module.reference", which when used without a Manager simply returns null. 

However, in version 2.0 that has also changed to be "module.include('script.js').call(some, args)" to actually throw a ReferenceError if used without a Manager. 

But yes, if you want to be able to call other scripts from within a script, stick with the manager. If you want a one-time function or config file (since Scriptor can load JSON in the same way require can), then isolated Scripts are sufficient.

**Comment by chengxuntao** [comment]
Very helpful!
Thanks again.
